Readme modified
getify/youperiod.app pull request #23
Opened 2022-07-05 17:08 UTC by detronetdip

#### Changes

I have added few badges, fixed some indentations and modified few text to enhance the look and readability  of the `README.md` file.

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2022-07-05 22:05 UTC, novonimo requested changes
not a vital suggestion but it may be helpful somewhere, add `yarn` command structures along with `npm`

2022-07-06 04:44 UTC, detronetdip commented
@novonimo  added.

2022-07-06 05:26 UTC, akashgk approved these changes

2022-07-06 07:05 UTC, novonimo approved these changes

2022-07-06 17:46 UTC, getify commented
LGTM

2022-07-06 17:46 UTC, merged